use olav::{PreEscaped, xml};

#[test]
fn atom_feed_example_from_readme() {
    let feed_title = "Example Feed";
    let feed_id = "urn:uuid:60a76e80-d399-11e9-b23e-2a8991f4d4ad";
    let updated = "2026-08-22T18:30:02Z";
    let author_name = "Jane Developer";
    let author_email = "jane@example.com";
    let is_published = true;

    let entries: Vec<(&str, &str, &str, &str)> = vec![
        (
            "1225c695-cfb8-4ebb-aaaa-80da344efa6a",
            "Atom-Powered Robots Run Amok",
            "2026-08-22T18:30:02Z",
            "<p>Some atom news with <em>embedded HTML</em>.</p>",
        ),
        (
            "b3f5df58-2f55-4b56-9c52-9d6e0d3d7a8b",
            "Macros in Rust",
            "2026-08-15T10:00:00Z",
            "<p>Why compile-time templates are <strong>great</strong>.</p>",
        ),
    ];

    let feed = xml! {
        ?xml version="1.0" encoding="utf-8"
        @comment " Atom 1.0 feed, generated by olav "
        feed(xmlns="http://www.w3.org/2005/Atom", [xml:lang]="en") {
            title(type="text") { @feed_title }
            subtitle { "An olav example feed." }
            id { @feed_id }
            updated { @updated }
            author {
                name { @author_name }
                email { @author_email }
            }
            [atom:link](rel="self", type="application/atom+xml", href="http://example.com/feed.atom") { }
            @if is_published {
                rights(type="text") { "© 2026 Example Inc." }
            }
            @for (eid, etitle, eupdated, econtent) in &entries {
                entry {
                    title(type="text") { @etitle }
                    id { "urn:uuid:" @eid }
                    updated { @eupdated }
                    summary(type="text") { "An atom-sized summary." }
                    @if econtent.contains('<') {
                        content(type="html") {
                            @cdata {
                                @PreEscaped(econtent)
                            }
                        }
                    }
                }
            }
        }
    };

    let s = feed.into_string();

    // Verify key parts are present
    assert!(s.starts_with("<?xml version=\"1.0\" encoding=\"utf-8\"?>"));
    assert!(s.contains("<!-- Atom 1.0 feed, generated by olav -->"));
    assert!(s.contains("xmlns=\"http://www.w3.org/2005/Atom\""));
    assert!(s.contains("xml:lang=\"en\""));
    assert!(s.contains("<title type=\"text\">Example Feed</title>"));
    assert!(s.contains("<name>Jane Developer</name>"));
    assert!(s.contains("<email>jane@example.com</email>"));
    assert!(s.contains("© 2026 Example Inc."));
    assert!(s.contains("<atom:link"));
    assert!(s.contains("Atom-Powered Robots Run Amok"));
    assert!(s.contains("<![CDATA[<p>Some atom news with <em>embedded HTML</em>.</p>]]>"));
    assert!(
        s.contains("<![CDATA[<p>Why compile-time templates are <strong>great</strong>.</p>]]>")
    );
    assert_eq!(s.matches("<entry>").count(), 2);
    assert_eq!(s.matches("</entry>").count(), 2);
    assert!(s.ends_with("</feed>"));
}
